services:
  grafana:
    image: grafana/grafana-enterprise
    container_name: grafana
    restart: unless-stopped
    ports:
     - '3000:3000'
    networks:
      - grafana_network  # Используем пользовательскую сеть

networks:
  grafana_network:
    driver: bridge  # Указываем тип сети bridge
